name: docker
type: poci
meta:
  category: devops
  tags:
    - docker
about:
  title: Docker
  description: Use the Docker CLI.
  icon: https://avatars.githubusercontent.com/u/5429470?s=200&v=4
tools:
  - name: docker
    description: use the docker cli
    parameters:
      type: object
      properties:
        args:
          type: array
          description: Arguments to pass to the Docker command
          items:
            type: string
      required:
        - args
    container:
      image: docker
      command:
        - '{{args|into}}'
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
