name: kubernetes
image: mcp/kubernetes
type: server
meta:
  category: devops
  tags:
    - kubernetes
    - devops
about:
  title: Kubernetes
  description: Connect to a Kubernetes cluster and manage it
  icon: https://avatars.githubusercontent.com/u/13629408?s=200&v=4
source:
  project: https://github.com/Flux159/mcp-server-kubernetes
